name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run : docker build --target test -t dumps ./src
    - name: Run tests
      run : docker run --rm dumps
            